<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./static/assets/computer.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/computer-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.redbutton.geometry}
      material={gltf.materials['Material.006']}
      position={[2.15, -0.9, -1.72]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
    />
    <T.Mesh
      geometry={gltf.nodes.glassscreen.geometry}
      material={gltf.materials.SCREEN}
      position={[1.9, -0.55, -0.55]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
    />
    <T.Mesh
      geometry={gltf.nodes.whitebutton.geometry}
      material={gltf.materials['Material.007']}
      position={[2.16, -0.9, -2.07]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
    />
    <T.Group position={[1.57, -0.86, -0.92]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
      <T.Mesh geometry={gltf.nodes.Cube004_0.geometry} material={gltf.materials['Material.014']} />
      <T.Mesh geometry={gltf.nodes.Cube004_0_1.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Cube004_0_2.geometry} material={gltf.materials['Material.009']} />
      <T.Mesh geometry={gltf.nodes.Cube004_0_3.geometry} material={gltf.materials['Material.010']} />
      <T.Mesh geometry={gltf.nodes.Cube004_0_4.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Cube004_0_5.geometry} material={gltf.materials['Material.003']} />
      <T.Mesh geometry={gltf.nodes.Cube004_0_6.geometry} material={gltf.materials['Material.008']} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes['switch'].geometry}
      material={gltf.materials['Material.008']}
      position={[1.51, -0.8, -1.7]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
    />
    <T.Mesh
      geometry={gltf.nodes.projection.geometry}
      material={gltf.materials['Material.014']}
      position={[1.57, -0.86, -0.92]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
