backend:
  name: git-gateway
  branch: master # or your default branch

# These lines should match your current setup
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"

# Enable editorial workflow for drafts
publish_mode: editorial_workflow

collections:
  - name: "linkpost"
    label: "Link Posts"
    folder: "src/content/links"
    create: true
    format: "mdx"
    slug: "{{year}}-{{week}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "URL", name: "url", widget: "string", required: true }
      - { 
          label: "Date", 
          name: "date", 
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "YYYY-MM-DD",
          time_format: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }

  - name: "blogpost"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    format: "mdx"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { 
          label: "Date", 
          name: "date", 
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "YYYY-MM-DD",
          time_format: false
        }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }

  - name: "work"
    label: "Work"
    folder: "src/content/work"
    create: true
    format: "mdx"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }

  - name: "tidytuesday"
    label: "Tidy Tuesday"
    folder: "src/content/tidytuesday"
    create: true
    format: "mdx"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
